# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coala
email: activismo.coala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nuestra misión es concientizar a las personas sobre la grave problemática
  de la explotación animal, alentarlas a hacerse veganas, acompañarlas en
  su transición e inspirarlas a involucrarse a través de activismo vegano
  no violento y efectivo.
baseurl: "/coala-website" # the subpath of your site, e.g. /blog
url: "http://coala.com.ar" # the base hostname & protocol for your site
twitter_username: coala.libre
github_username:  nicanor
permalink: pretty

# Build settings
markdown: kramdown
include: ["_pages"]